---
stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ21N22"
    source: helloworldclone
    npmExecuteLint: false
  malwareScan:
    scan: false
  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com/"
      org: "30ad7580trial"
      space: "dev"
      credential: "deployonbtp"
